Move the database schema to /schema

diff --git a/schema/skeema b/schema/skeema
--- a/schema/skeema
+++ b/schema/skeema
@@ -5,8 +5,8 @@ cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
 
 if [[ "$2" =~ ^(production)$ ]]; then
     >&2 echo "Skeema is executing for a known environment, setting mysql password from AWS SecretsSmanager"
-    MYSQL_PWD=$(../node_modules/.bin/tsx ../bin/database-password.ts "$2") || (>&2 echo "Error getting password for environment")
+    MYSQL_PWD=$(pnpm database-password "$2") || (>&2 echo "Error getting password for environment")
     export MYSQL_PWD
 fi
 
-../vendor/skeema_linux "$@"
+./vendor/skeema_linux "$@"
